#
# docker-compose.yml: Docker Compose configuration to build and run a container
# that generates a WireGuard VPN configuration using Private Internet Access (PIA)
# manual connection scripts and necessary WireGuard tools.
#
# Learn more about manual PIA VPN connections here: https://github.com/pia-foss/manual-connections
#

#
# Define the services used in this stack
#
services:
  #
  # Configure the 'privateerr' service
  #
  privateerr:
    # Docker image build and container information
    image: ${PRIVATEERR_IMAGE}:${PRIVATEERR_TAG}       # Set the image name and tag for the container
    build:                                             # Define build context and arguments
      context: docker                                  # Directory containing the Dockerfile
      dockerfile: Dockerfile                           # Dockerfile used for building the image
      args:                                            # Arguments passed to the Dockerfile build stage
        UBUNTU_TAG: ${UBUNTU_TAG}                      # Base Ubuntu image version
        TZ: ${TZ}                                      # Time zone configuration
        PIA_APP_HOME: ${PIA_APP_HOME}                  # Directory where PIA scripts will reside
    container_name: privateerr-${PRIVATEERR_TAG}       # Container name including the tag
    restart: no                                        # Container will not restart automatically
    network_mode: bridge                               # Use Docker's default bridge network
    hostname: privateerr                               # Set hostname inside the container
    privileged: true                                   # Required for network configuration tasks
    labels:                                            # Apply Docker labels to the container
      - "com.centurylinklabs.watchtower.enable=false"  # Prevent Watchtower from updating this container

    # Define the container environment
    environment:
      VPN_PROTOCOL: ${PIA_VPN_PROTOCOL}  # VPN type: wireguard or openvpn
      DISABLE_IPV6: ${PIA_DISABLE_IPV6}  # Disable IPv6: yes or no
      DIP_TOKEN: ${PIA_DIP_TOKEN}        # Optional: PIA dedicated IP token, or set to 'no'
      AUTOCONNECT: ${PIA_AUTOCONNECT}    # Auto-select the server with the lowest latency: true or false
      PIA_CONF_PATH: ${PIA_CONF_PATH}    # Path where the WireGuard config file will be generated
      PIA_CONNECT: ${PIA_CONNECT}        # Connect to VPN after config generation: true or false
      PIA_PF: ${PIA_PF}                  # Enable port forwarding: true or false
      PIA_DNS: ${PIA_DNS}                # Configure DNS settings: true or false
      PIA_USER: ${PIA_USER}              # PIA account username
      PIA_PASS: ${PIA_PASS}              # PIA account password

    # Mount host directories into the container
    volumes:
      - ${HOST_CONF_PATH}:/${PIA_CONF_PATH}:rw  # Mount host directory for WireGuard config output
