blank_issues_enabled: false

contact_links:
  - name: 🔥HADES🔥
    url: https://discord.gg/BpEGzWwGYf
    about: When the VPN spirits revolt and chaos rises, descend into ⛧ HADES ⛧ and seek aid from the fireproof crew
