#
# Copyright 2025-2026 Scott Gigawatt
#
# Licensed under the Apache License, Version 2.0.
#
# privateerr-vpn-settings.jq: Validate generated files and build a minimal Gluetun update.
#
# Input: $config contains wg0.conf; $metadata contains privateerr.env.
# Output: Connection settings accepted by PUT /v1/vpn/settings, or a validation error.
#

#
# Parse assignments without evaluating shell content; reject duplicate field names.
#
def assignments:
  reduce (
    split("\n")[]
    | select(test("^[A-Za-z_]+\\s*="))
    | capture("^(?<key>[A-Za-z_]+)\\s*=\\s*(?<value>.*?)\\s*$")
  ) as $line (
    {};

    if has($line.key) then
      error("Duplicate configuration field")
    else
      .[$line.key] = $line.value
    end
  );

#
# Require four decimal octets in the IPv4 addresses generated by PIA.
#
def ipv4:
  split(".") as $parts
  | ($parts | length) == 4
    and all($parts[]; test("^[0-9]{1,3}$") and (tonumber <= 255));

#
# Require the base64 shape of a 32-byte WireGuard key without printing its value.
#
def key:
  test("^[A-Za-z0-9+/]{43}=$");

#
# Read the files separately so their endpoint values can be checked for agreement.
#
($config | assignments) as $wg
| ($metadata | assignments) as $meta
| ($wg.Endpoint // "" | split(":")) as $endpoint
| ($wg.Address // "" | split("/")) as $address

#
# Validate keys, endpoint, interface address, and matching PIA metadata before building an update.
#
| if (
    ($wg.PrivateKey // "" | key)
    and ($wg.PublicKey // "" | key)

    #
    # WireGuard needs one IPv4 endpoint and a valid UDP port.
    #
    and ($endpoint | length) == 2
    and ($endpoint[0] | ipv4)
    and ($endpoint[1] | test("^[0-9]{1,5}$"))
    and ($endpoint[1] | tonumber) > 0
    and ($endpoint[1] | tonumber) <= 65535

    #
    # An omitted interface prefix becomes /32 in the API request.
    #
    and ($address | length) <= 2
    and ($address[0] | ipv4)
    and (($address[1] // "32") | test("^([0-9]|[12][0-9]|3[0-2])$"))

    #
    # Keep the PIA TLS server name and endpoint metadata consistent with the config.
    #
    and ($meta.PIA_WG_SERVER_NAME // "" | test("^[A-Za-z0-9][A-Za-z0-9.-]*$"))
    and $meta.PIA_WG_ENDPOINT_IP == $endpoint[0]
    and $meta.PIA_WG_ENDPOINT_PORT == $endpoint[1]
  ) then

    #
    # Include only connection fields so Gluetun preserves unrelated settings.
    #
    {
      wireguard: {
        private_key: $wg.PrivateKey,
        addresses: [($address[0] + "/" + ($address[1] // "32"))]
      },
      provider: {
        server_selection: {
          names: [$meta.PIA_WG_SERVER_NAME],
          wireguard: {
            endpoint_ip: $endpoint[0],
            endpoint_port: ($endpoint[1] | tonumber),
            public_key: $wg.PublicKey
          }
        }
      }
    }
  else
    error("Generated WireGuard configuration or metadata is invalid")
  end
